<a href="https://colab.research.google.com/github/kxrrym03/VALORANT-Champions-Tour-2025/blob/main/VALORANT_champions_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
from google.colab import files
upload = files.upload()

Saving vct2025_01_partnered_teams.csv to vct2025_01_partnered_teams.csv

In [6]:
df = pd.read_csv('vct2025_01_partnered_teams.csv')
df.shape

(48, 6)

In [5]:
df.head()

,team_name,region,league,country,team_type,league_location
0,NRG Esports,Americas,VCT Americas 2025,United States,Partner,"Los Angeles, USA"
1,Sentinels,Americas,VCT Americas 2025,United States,Partner,"Los Angeles, USA"
2,Cloud9,Americas,VCT Americas 2025,United States,Partner,"Los Angeles, USA"
3,100 Thieves,Americas,VCT Americas 2025,United States,Partner,"Los Angeles, USA"
4,LOUD,Americas,VCT Americas 2025,Brazil,Partner,"Los Angeles, USA"

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.isnull().sum()

team_name          0
region             0
league             0
country            0
team_type          0
league_location    0
dtype: int64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   team_name        48 non-null     object
 1   region           48 non-null     object
 2   league           48 non-null     object
 3   country          48 non-null     object
 4   team_type        48 non-null     object
 5   league_location  48 non-null     object
dtypes: object(6)
memory usage: 2.4+ KB

In [12]:
df.describe()

,team_name,region,league,country,team_type,league_location
count,48,48,48,48,48,48
unique,48,4,4,20,4,4
top,NRG Esports,Americas,VCT Americas 2025,China,Partner,"Los Angeles, USA"
freq,1,12,12,12,40,12

In [13]:
df.dtypes

team_name          object
region             object
league             object
country            object
team_type          object
league_location    object
dtype: object